{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "application-catalog.fullname" . }}-validating
  labels:
    {{- include "application-catalog.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "application-catalog.fullname" . }}-webhook-cert
  {{- end }}
webhooks:
  - name: validate.applicationcatalog.k8c.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "application-catalog.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-applicationcatalog-k8c-io-v1alpha1-applicationcatalog
        port: {{ .Values.webhook.port }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - applicationcatalog.k8c.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - applicationcatalogs
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 10
{{- end }}
