{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application-catalog.fullname" . }}-webhook
  labels:
    {{- include "application-catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
automountServiceAccountToken: true
{{- end }}
