{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-catalog.fullname" . }}-webhook
  labels:
    {{- include "application-catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "application-catalog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
{{- end }}
